name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  ubuntu:
    name: "Ubuntu"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['23.3', '24.2', '25.2']
        rebar: ['3.20.0']
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar}}
    - name: Tests
      run: make test
  windows:
    name: "Windows"
    runs-on: windows-latest
    strategy:
      matrix:
        otp: ['23.3', '24.2', '25.2']
        rebar: ['3.20.0']
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar}}
    - name: Tests
      run: make test
